package enums;

public enum ClassCategory {
    // Online Classes
    INTERNATIONAL_ONLINE_INDIVIDUAL_ALL_CATEGORIES,
    SCHOOL_CLASS_ONLINE_GRADE_6_PLUS_GROUP,
    ELDERS_CLASS_ONLINE_18_PLUS_GROUP,

    // Physical Classes
    KIDS_CLASS_PHYSICAL_4_10_GROUP,
    SCHOOL_CLASS_PHYSICAL_10_18_GROUP,
    ELDERS_CLASS_PHYSICAL_18_PLUS_PROFESSIONALS_GROUP
}
